### ISSUE TITLE
Recommended: What is Functional Programming, by Kris Jenkins

### ISSUE THREAD

**Issue by jfmengels** [joshburgess/my-favorite-talks#1]
I definitely recommend Kris Jenkins' talk on "What is Functional Programming?" ;)

https://www.youtube.com/watch?v=tQRtTSIpye4

**Comment by joshburgess** [comment]
Thanks, I'll give it a watch! :)

**Comment by joshburgess** [comment]
Watched and put it on the list! Thanks. Let me know if you have any others.

**Comment by jfmengels** [comment]
Cool! :D
